models:
  primary: { provider: openai, model: gpt-4.1-nano, env_var1: OPENAI_API_KEY_CLAN }
  jury:
    [
      { provider: openai, model: gpt-4.1-nano, env_var1: OPENAI_API_KEY_CLAN },
      { provider: openai, model: gpt-4.1-nano, env_var2: OPENAI_API_KEY_CLAN },
      { provider: openai, model: gpt-4.1-nano, env_var3: OPENAI_API_KEY_CLAN },
    ]
